version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474" # Web interface
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/melancia # Username/password
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1024m
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./conf:/conf
